#defaults:
#  - opt: adamw
#  # - override hydra/launcher: joblib
#  - _self_

weight_decay: 0.0
learning_rate: 1e-4

model_name: microsoft/deberta-v3-small
batch_size: 128
micro_batch_size: 4
name: ???
seed: 31
dbg: false
verbose: true
train_steps: 64000
evaluate_every: epoch  # 1000 or 1 or any num step
wandb_tag: ???
use_batch_norm: false
full_batch_val: true

dataset_name: 'wikitext2raw'
max_text_tokens: inf
max_chunk_size: 14
max_chunks_number: 32
min_tokens: 1
min_chunks: 1


num_workers_dl: 16
prefetch_factor_dl: 32
